apiVersion: v1
kind: Service
metadata:
  name: memcached
  labels:
    tier: memcached
    role: memcached
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port:   '9150'
spec:
  selector:
    app: memcached
    tier: memcached
  ports:
  - name: memcached
    protocol: TCP
    port: 11211
    targetPort: 11211
  type: ClusterIP
